export type Difficulty = 'Beginner' | 'Intermediate' | 'Advanced'

export type CatalogEntry = {
  id: string
  name: string
  difficulty: Difficulty
  benefits: string
}

export const catalog: CatalogEntry[] = [
  // ─── Beginner ───────────────────────────────────────────────────────────
  { id: 'mountain', name: 'Mountain Pose', difficulty: 'Beginner', benefits: 'Improves posture and stability; foundation for standing positions.' },
  { id: 'standing-forward-fold', name: 'Standing Forward Fold', difficulty: 'Beginner', benefits: 'Stretches hamstrings, calves, and lower back.' },
  { id: 'half-forward-fold', name: 'Half Forward Fold', difficulty: 'Beginner', benefits: 'Lengthens the spine and stretches the hamstrings.' },
  { id: 'easy', name: 'Easy Seated Pose', difficulty: 'Beginner', benefits: 'Opens hips and promotes comfortable seated posture.' },
  { id: 'staff', name: 'Staff Pose', difficulty: 'Beginner', benefits: 'Strengthens core and improves seated alignment.' },
  { id: 'child', name: "Child's Pose", difficulty: 'Beginner', benefits: 'Stretches lower back, hips, and thighs; gentle recovery position.' },
  { id: 'corpse', name: 'Corpse Pose', difficulty: 'Beginner', benefits: 'Promotes full-body relaxation and reduces nervous-system activation.' },
  { id: 'cat', name: 'Cat Stretch', difficulty: 'Beginner', benefits: 'Mobilizes spine into flexion; activates abdominal muscles.' },
  { id: 'cow', name: 'Cow Stretch', difficulty: 'Beginner', benefits: 'Mobilizes spine into extension; opens the chest.' },
  { id: 'thread-needle', name: 'Thread the Needle', difficulty: 'Beginner', benefits: 'Stretches upper back, shoulders, and the rotator cuff area.' },
  { id: 'cobra', name: 'Cobra', difficulty: 'Beginner', benefits: 'Strengthens spinal extensors; opens chest and front of shoulders.' },
  { id: 'sphinx', name: 'Sphinx', difficulty: 'Beginner', benefits: 'Gentle back extension; strengthens lumbar spine and opens chest.' },
  { id: 'locust', name: 'Locust', difficulty: 'Beginner', benefits: 'Strengthens posterior chain — back, glutes, hamstrings.' },
  { id: 'bridge', name: 'Bridge', difficulty: 'Beginner', benefits: 'Strengthens glutes and hamstrings; opens chest and hip flexors.' },
  { id: 'reclining-bound-angle', name: 'Reclining Butterfly', difficulty: 'Beginner', benefits: 'Passively opens hips and stretches inner thighs.' },
  { id: 'bound-angle', name: 'Butterfly (Seated)', difficulty: 'Beginner', benefits: 'Stretches inner thighs and groin; opens hips.' },
  { id: 'happy-baby', name: 'Happy Baby', difficulty: 'Beginner', benefits: 'Stretches lower back and inner thighs; releases hip tension.' },
  { id: 'legs-up-wall', name: 'Legs Up the Wall', difficulty: 'Beginner', benefits: 'Reduces leg swelling and aids venous return after activity.' },
  { id: 'supine-twist', name: 'Reclined Spinal Twist', difficulty: 'Beginner', benefits: 'Stretches lower back, glutes, and obliques; mobilizes spine.' },
  { id: 'seated-forward-fold', name: 'Seated Forward Fold', difficulty: 'Beginner', benefits: 'Stretches hamstrings, calves, and the full posterior spine.' },
  { id: 'tree', name: 'Tree Pose', difficulty: 'Beginner', benefits: 'Improves single-leg balance; strengthens ankles and stabilizers.' },
  { id: 'warrior-1', name: 'Warrior I', difficulty: 'Beginner', benefits: 'Strengthens legs; stretches hip flexors and chest.' },
  { id: 'warrior-2', name: 'Warrior II', difficulty: 'Beginner', benefits: 'Strengthens legs, hips, and shoulders; builds endurance.' },
  { id: 'chair', name: 'Chair Pose', difficulty: 'Beginner', benefits: 'Strengthens quads, glutes, and core; builds lower-body endurance.' },
  { id: 'triangle', name: 'Triangle Pose', difficulty: 'Beginner', benefits: 'Stretches hamstrings, hips, and the side body.' },
  { id: 'downward-dog', name: 'Downward Dog', difficulty: 'Beginner', benefits: 'Stretches hamstrings, calves, and shoulders; full-body engagement.' },
  { id: 'plank', name: 'Plank', difficulty: 'Beginner', benefits: 'Strengthens core, shoulders, and arms; builds total-body tension.' },
  { id: 'garland', name: 'Deep Squat', difficulty: 'Beginner', benefits: 'Opens hips, ankles, and groin; improves squat mobility.' },
  { id: 'high-lunge', name: 'High Lunge', difficulty: 'Beginner', benefits: 'Stretches hip flexors; strengthens legs and glutes.' },
  { id: 'low-lunge', name: 'Low Lunge', difficulty: 'Beginner', benefits: 'Deep hip-flexor stretch; opens the groin.' },
  { id: 'goddess', name: 'Goddess Squat', difficulty: 'Beginner', benefits: 'Strengthens inner thighs and glutes; opens hips.' },
  { id: 'upward-salute', name: 'Upward Salute', difficulty: 'Beginner', benefits: 'Lengthens the spine and opens shoulders; preparation for backbends.' },
  { id: 'wide-leg-forward-fold', name: 'Wide-Leg Standing Forward Fold', difficulty: 'Beginner', benefits: 'Stretches inner thighs, hamstrings, and lower back.' },
  { id: 'reverse-warrior', name: 'Reverse Warrior', difficulty: 'Beginner', benefits: 'Stretches side body and intercostals; strengthens legs.' },
  { id: 'ragdoll', name: 'Ragdoll Pose', difficulty: 'Beginner', benefits: 'Releases tension in neck, shoulders, and lower back through gentle hanging.' },
  { id: 'knees-to-chest', name: 'Knees-to-Chest', difficulty: 'Beginner', benefits: 'Releases lower-back tension; gentle abdominal compression.' },
  { id: 'eye-of-needle', name: 'Eye of the Needle', difficulty: 'Beginner', benefits: 'Opens outer hips and glutes; gentle prep for Pigeon.' },
  { id: 'reclined-big-toe', name: 'Reclined Hand-to-Big-Toe', difficulty: 'Beginner', benefits: 'Hamstring stretch with full spinal support.' },
  { id: 'seated-side-bend', name: 'Seated Side Bend', difficulty: 'Beginner', benefits: 'Stretches the side body, obliques, and intercostal muscles.' },
  { id: 'mountain-side-bend', name: 'Mountain with Side Bend', difficulty: 'Beginner', benefits: 'Opens the lateral body while building standing stability.' },
  { id: 'seated-twist', name: 'Easy Seated Twist', difficulty: 'Beginner', benefits: 'Gentle spinal rotation; aids digestion and thoracic mobility.' },
  { id: 'constructive-rest', name: 'Constructive Rest', difficulty: 'Beginner', benefits: 'Releases lower back and psoas; full-body relaxation position.' },
  { id: 'ankle-to-knee', name: 'Ankle-to-Knee Stretch', difficulty: 'Beginner', benefits: 'Deep outer hip stretch; opens hip rotators.' },
  { id: 'low-cobra', name: 'Low Cobra', difficulty: 'Beginner', benefits: 'Gentle back extension with no arm push; isolates spinal extensors.' },
  { id: 'half-pigeon', name: 'Half Pigeon', difficulty: 'Beginner', benefits: 'Less-intense version of Pigeon; opens the outer hip safely.' },
  { id: 'bird-dog', name: 'Bird Dog', difficulty: 'Beginner', benefits: 'Core stabilization with cross-body coordination; strengthens the back.' },
  { id: 'wall-squat', name: 'Wall Squat', difficulty: 'Beginner', benefits: 'Builds quad and glute endurance; safer than free-standing squats for knees.' },
  { id: 'standing-side-bend', name: 'Standing Side Bend', difficulty: 'Beginner', benefits: 'Mobilizes the spine laterally; opens the ribs.' },
  { id: 'three-legged-dog', name: 'Three-Legged Dog', difficulty: 'Beginner', benefits: 'Hamstring stretch with hip opener; preparation for inversions.' },
  { id: 'figure-4', name: 'Figure 4 Stretch', difficulty: 'Beginner', benefits: 'Outer hip and glute stretch; can be done lying or standing.' },
  { id: 'banana', name: 'Banana Pose', difficulty: 'Beginner', benefits: 'Releases the side body, intercostals, and IT band.' },

  // ─── Intermediate ───────────────────────────────────────────────────────
  { id: 'warrior-3', name: 'Warrior III', difficulty: 'Intermediate', benefits: 'Strengthens legs and core; challenges single-leg balance.' },
  { id: 'half-moon', name: 'Half Moon', difficulty: 'Intermediate', benefits: 'Strengthens legs and core; demands balance and hip stability.' },
  { id: 'pyramid', name: 'Pyramid Pose', difficulty: 'Intermediate', benefits: 'Deep hamstring stretch; challenges balance.' },
  { id: 'eagle', name: 'Eagle Pose', difficulty: 'Intermediate', benefits: 'Stretches shoulders and upper back; improves balance.' },
  { id: 'dancer', name: 'Dancer Pose', difficulty: 'Intermediate', benefits: 'Stretches chest and quads; challenges balance.' },
  { id: 'side-angle', name: 'Extended Side Angle', difficulty: 'Intermediate', benefits: 'Stretches side body and groin; strengthens legs.' },
  { id: 'half-lord-of-fishes', name: 'Seated Spinal Twist', difficulty: 'Intermediate', benefits: 'Mobilizes thoracic spine; stretches glutes and obliques.' },
  { id: 'revolved-triangle', name: 'Revolved Triangle', difficulty: 'Intermediate', benefits: 'Mobilizes thoracic spine; stretches hamstrings.' },
  { id: 'revolved-chair', name: 'Revolved Chair', difficulty: 'Intermediate', benefits: 'Stretches obliques and spine; strengthens legs.' },
  { id: 'head-to-knee', name: 'Head-to-Knee Stretch', difficulty: 'Intermediate', benefits: 'Stretches hamstrings, hips, and the lower back.' },
  { id: 'wide-angle-fold', name: 'Wide-Leg Forward Fold (Seated)', difficulty: 'Intermediate', benefits: 'Stretches inner thighs and hamstrings.' },
  { id: 'cow-face', name: 'Cow-Face Stretch', difficulty: 'Intermediate', benefits: 'Stretches shoulders, chest, and outer hips.' },
  { id: 'hero', name: 'Hero Pose', difficulty: 'Intermediate', benefits: 'Stretches quadriceps and ankles; mobilizes knees.' },
  { id: 'pigeon', name: 'Pigeon Stretch', difficulty: 'Intermediate', benefits: 'Deep hip and glute stretch; opens the hip rotators.' },
  { id: 'lizard', name: 'Lizard Lunge', difficulty: 'Intermediate', benefits: 'Deep hip-flexor and inner-thigh stretch.' },
  { id: 'frog', name: 'Frog Stretch', difficulty: 'Intermediate', benefits: 'Stretches inner thighs and opens the hips wide.' },
  { id: 'half-lotus', name: 'Half-Crossed-Leg Sit', difficulty: 'Intermediate', benefits: 'Opens hips and requires external rotation.' },
  { id: 'boat', name: 'Boat Pose', difficulty: 'Intermediate', benefits: 'Strengthens core and hip flexors.' },
  { id: 'upward-dog', name: 'Upward-Facing Dog', difficulty: 'Intermediate', benefits: 'Strengthens arms and back; opens the chest.' },
  { id: 'camel', name: 'Camel Pose', difficulty: 'Intermediate', benefits: 'Deep backbend; opens chest and hip flexors.' },
  { id: 'bow', name: 'Bow Pose', difficulty: 'Intermediate', benefits: 'Strengthens back; stretches chest, hips, and quads.' },
  { id: 'fish', name: 'Fish Pose', difficulty: 'Intermediate', benefits: 'Opens chest and throat; strengthens upper back.' },
  { id: 'dolphin', name: 'Dolphin', difficulty: 'Intermediate', benefits: 'Strengthens shoulders and core; prep work for inversions.' },
  { id: 'side-plank', name: 'Side Plank', difficulty: 'Intermediate', benefits: 'Strengthens obliques, shoulders, and arms.' },
  { id: 'crow', name: 'Crow Pose', difficulty: 'Intermediate', benefits: 'Strengthens arms, wrists, and core; entry to arm balancing.' },
  { id: 'plow', name: 'Plow Pose', difficulty: 'Intermediate', benefits: 'Stretches shoulders, spine, and hamstrings; gentle inversion.' },
  { id: 'crescent-lunge', name: 'Crescent Lunge', difficulty: 'Intermediate', benefits: 'Deep hip-flexor stretch with overhead arm extension.' },
  { id: 'standing-splits', name: 'Standing Splits', difficulty: 'Intermediate', benefits: 'Hamstring flexibility while balancing on one leg; preps for inversions.' },
  { id: 'compass', name: 'Compass Pose', difficulty: 'Intermediate', benefits: 'Hamstring, hip, and shoulder opener combined; challenges flexibility broadly.' },
  { id: 'mermaid', name: 'Mermaid Pose', difficulty: 'Intermediate', benefits: 'Deep hip-flexor and shoulder stretch; full side-body engagement.' },
  { id: 'bird-of-paradise-prep', name: 'Bird of Paradise Prep', difficulty: 'Intermediate', benefits: 'Hamstring flexibility with bound shoulders; prep for the full pose.' },
  { id: 'chaturanga', name: 'Chaturanga', difficulty: 'Intermediate', benefits: 'Builds tricep, shoulder, and core strength; foundational Vinyasa transition.' },
  { id: 'half-splits', name: 'Half Splits', difficulty: 'Intermediate', benefits: 'Hamstring stretch with extended forward fold; prep for full splits.' },
  { id: 'twisted-lizard', name: 'Twisted Lizard', difficulty: 'Intermediate', benefits: 'Hip-flexor and quad stretch combined with thoracic rotation.' },
  { id: 'eagle-twist', name: 'Eagle with Twist', difficulty: 'Intermediate', benefits: 'Shoulder and hip stretch with deep core engagement.' },
  { id: 'marichi-twist', name: "Marichi's Twist", difficulty: 'Intermediate', benefits: 'Deep seated spinal twist with bound arm; intense mid-back rotation.' },
  { id: 'heron', name: 'Heron Pose', difficulty: 'Intermediate', benefits: 'Intense hamstring stretch in a seated position.' },
  { id: 'side-pigeon', name: 'Side-Lying Pigeon', difficulty: 'Intermediate', benefits: 'Reclined outer-hip stretch with spinal alignment maintained.' },
  { id: 'twisted-pyramid', name: 'Twisted Pyramid', difficulty: 'Intermediate', benefits: 'Hamstring stretch combined with thoracic spine rotation.' },
  { id: 'cow-face-eagle-arms', name: 'Cow Face with Eagle Arms', difficulty: 'Intermediate', benefits: 'Maximum shoulder and outer-hip flexibility test.' },
  { id: 'twisted-boat', name: 'Twisted Boat', difficulty: 'Intermediate', benefits: 'Strengthens core and oblique muscles with rotational load.' },
  { id: 'bound-side-angle', name: 'Bound Side Angle', difficulty: 'Intermediate', benefits: 'Side-body stretch with deep shoulder opener through the bound arm.' },
  { id: 'half-frog', name: 'Half Frog', difficulty: 'Intermediate', benefits: 'Quad stretch with mild backbend; opens hip flexors.' },
  { id: 'revolved-half-moon', name: 'Revolved Half Moon', difficulty: 'Intermediate', benefits: 'Single-leg balance with deep spinal twist.' },
  { id: 'tripod-headstand-prep', name: 'Tripod Headstand Prep', difficulty: 'Intermediate', benefits: 'Builds inversion confidence; strengthens shoulders and arms.' },
  { id: 'sugarcane', name: 'Sugarcane Pose', difficulty: 'Intermediate', benefits: 'Half Moon variation with quad and chest stretch; balance challenge.' },
  { id: 'revolved-pigeon', name: 'Revolved Pigeon', difficulty: 'Intermediate', benefits: 'Hip opener combined with thoracic spinal twist.' },
  { id: 'shoulder-pressing', name: 'Shoulder Pressing Pose', difficulty: 'Intermediate', benefits: 'Arm balance preparation; builds shoulder and arm strength.' },
  { id: 'wild-thing', name: 'Wild Thing', difficulty: 'Intermediate', benefits: 'Chest and hip-flexor opener with single-arm support; heart-opening flow.' },
  { id: 'sleeping-vishnu', name: 'Sleeping Vishnu', difficulty: 'Intermediate', benefits: 'Side-lying hamstring flexibility with balance.' },
  { id: 'revolved-warrior', name: 'Revolved Warrior I', difficulty: 'Intermediate', benefits: 'Hip-flexor stretch with deep spinal rotation.' },

  // ─── Advanced ───────────────────────────────────────────────────────────
  { id: 'lotus', name: 'Full Crossed-Leg Sit', difficulty: 'Advanced', benefits: 'Requires significant external rotation of the hips; opens the lower body.' },
  { id: 'wheel', name: 'Wheel / Backbend', difficulty: 'Advanced', benefits: 'Deep backbend; requires shoulder and hip flexibility plus strength.' },
  { id: 'shoulder-stand', name: 'Shoulder Stand', difficulty: 'Advanced', benefits: 'Full inversion; demands neck mobility and core control.' },
  { id: 'headstand', name: 'Headstand', difficulty: 'Advanced', benefits: 'Full inversion; demands core stability and shoulder strength.' },
  { id: 'forearm-stand', name: 'Forearm Stand', difficulty: 'Advanced', benefits: 'Advanced inversion; demands shoulder strength and balance.' },
  { id: 'handstand', name: 'Handstand', difficulty: 'Advanced', benefits: 'Full inversion; demands arm/shoulder strength and fine balance.' },
  { id: 'side-crow', name: 'Side Crow', difficulty: 'Advanced', benefits: 'Advanced arm balance; demands oblique strength and wrist tolerance.' },
  { id: 'eight-angle', name: 'Eight-Angle Pose', difficulty: 'Advanced', benefits: 'Advanced arm balance; demands core, hip flexibility, and arm strength.' },
  { id: 'firefly', name: 'Firefly Pose', difficulty: 'Advanced', benefits: 'Advanced arm balance; demands hamstring flexibility and arm strength.' },
  { id: 'full-splits', name: 'Full Splits (Front)', difficulty: 'Advanced', benefits: 'Maximum hamstring of front leg and hip-flexor of back leg; benchmark flexibility.' },
  { id: 'middle-splits', name: 'Middle Splits', difficulty: 'Advanced', benefits: 'Maximum inner-thigh and adductor flexibility; rare even in advanced practitioners.' },
  { id: 'bird-of-paradise', name: 'Bird of Paradise', difficulty: 'Advanced', benefits: 'Hamstring, hip, and shoulder mobility tested simultaneously while balancing.' },
  { id: 'king-pigeon', name: 'King Pigeon', difficulty: 'Advanced', benefits: 'Maximum hip-flexor and back extension; bound foot brought toward the head.' },
  { id: 'scorpion', name: 'Scorpion Pose', difficulty: 'Advanced', benefits: 'Forearm balance with deep backbend; integrates strength and flexibility.' },
  { id: 'flying-pigeon', name: 'Flying Pigeon', difficulty: 'Advanced', benefits: 'Arm balance with hip rotation; demands wrist strength and hip mobility.' },
  { id: 'one-legged-crow', name: 'One-Legged Crow', difficulty: 'Advanced', benefits: 'Arm balance with single-leg extension; advanced core and balance.' },
  { id: 'tortoise', name: 'Tortoise Pose', difficulty: 'Advanced', benefits: 'Extreme hip and hamstring flexibility within a deep forward fold.' },
  { id: 'peacock', name: 'Peacock Pose', difficulty: 'Advanced', benefits: 'Wrist and arm strength; full-body horizontal hold balanced on forearms.' },
  { id: 'side-plank-splits', name: 'Side Plank Splits', difficulty: 'Advanced', benefits: 'Side plank combined with hamstring flexibility — strength and mobility together.' },
  { id: 'crane', name: 'Crane Pose', difficulty: 'Advanced', benefits: 'Straight-armed version of Crow; demands more shoulder and core strength.' },
  { id: 'inverted-staff', name: 'Inverted Staff Pose', difficulty: 'Advanced', benefits: 'Forearm-supported deep backbend; preparation for full forearm-stand wheel.' },
  { id: 'press-handstand', name: 'Press to Handstand', difficulty: 'Advanced', benefits: 'Strength-based handstand entry; demands compression strength and balance.' },
  { id: 'lotus-headstand', name: 'Headstand with Crossed Legs', difficulty: 'Advanced', benefits: 'Inversion combined with deep hip rotation; tests inversion control.' },
  { id: 'wounded-peacock', name: 'Wounded Peacock', difficulty: 'Advanced', benefits: 'One-armed variation of Peacock; extreme wrist and shoulder strength.' },
]
