import type { Session } from './sessions'

export const strengthSessions: Session[] = [
  {
    id: 'str-core-crusher',
    name: 'Core Crusher',
    focus: 'Six-Pack Focus',
    difficulty: 'Intermediate',
    durationMin: 10,
    icon: '🔥',
    gradient: 'from-orange-600 via-red-700 to-rose-800',
    description:
      'A dense ab session. Targets the full rectus, obliques, and deep core. Move briskly between exercises.',
    modality: 'strength',
    steps: [
      { poseId: 'str-plank', durationSec: 45, cue: 'Hips level. Squeeze glutes. Long body.' },
      { poseId: 'str-leg-raise', durationSec: 45, cue: '12–15 reps. Lower slowly.' },
      { poseId: 'str-bicycle', durationSec: 45, cue: 'Slow rotation. Elbow to opposite knee.' },
      { poseId: 'str-side-plank', durationSec: 30, perSide: true },
      { poseId: 'str-russian-twist', durationSec: 45 },
      { poseId: 'str-hollow-hold', durationSec: 30, cue: 'Lower back glued down. Limbs hover.' },
      { poseId: 'str-v-up', durationSec: 45, cue: '10–12 reps. Strong contraction at the top.' },
      { poseId: 'str-toe-touch', durationSec: 30 },
      { poseId: 'str-dead-bug', durationSec: 45 },
      { poseId: 'str-mountain-climbers', durationSec: 60, cue: 'Pace yourself. Steady breath.' },
    ],
  },
  {
    id: 'str-push-pecs',
    name: 'Push & Pecs',
    focus: 'Chest Focus',
    difficulty: 'Intermediate',
    durationMin: 12,
    icon: '💪',
    gradient: 'from-zinc-700 via-stone-700 to-amber-800',
    description:
      'Bodyweight chest and shoulder builder. Wide push-ups for pec width, decline for upper chest, diamond for triceps.',
    modality: 'strength',
    steps: [
      { poseId: 'str-pushup', durationSec: 45, cue: 'Warm-up set. 10–12 reps.' },
      { poseId: 'str-wide-pushup', durationSec: 45, cue: '8–10 reps. Squeeze the chest at the top.' },
      { poseId: 'str-decline-pushup', durationSec: 45, cue: 'Feet on chair. 8–10 reps. Upper chest.' },
      { poseId: 'str-diamond-pushup', durationSec: 45, cue: '6–10 reps. Triceps + inner chest.' },
      { poseId: 'str-pike-pushup', durationSec: 45, cue: '6–10 reps. Hips high, head drives down.' },
      { poseId: 'str-wide-pushup', durationSec: 45, cue: 'Second set. To failure if you can.' },
      { poseId: 'str-plank', durationSec: 45, cue: 'Hold and breathe. Earn the rest.' },
      { poseId: 'str-pushup', durationSec: 45, cue: 'Finisher set. Whatever you have left.' },
    ],
  },
  {
    id: 'str-full-body',
    name: 'Full Body Burner',
    focus: 'Full Body',
    difficulty: 'Intermediate',
    durationMin: 15,
    icon: '⚡',
    gradient: 'from-amber-600 via-orange-700 to-red-800',
    description:
      'Full-body conditioning. Push, core, lower body, burpees. Strong fat-loss stimulus when run hard.',
    modality: 'strength',
    steps: [
      { poseId: 'str-squat', durationSec: 45, cue: 'Warm up the legs. 15 reps.' },
      { poseId: 'str-pushup', durationSec: 45, cue: '10–15 reps.' },
      { poseId: 'str-mountain-climbers', durationSec: 45 },
      { poseId: 'str-burpee', durationSec: 45, cue: '6–10 reps. Full extension.' },
      { poseId: 'str-leg-raise', durationSec: 45 },
      { poseId: 'str-jumping-squat', durationSec: 30, cue: 'Explosive. 8–12 reps.' },
      { poseId: 'str-wide-pushup', durationSec: 45 },
      { poseId: 'str-russian-twist', durationSec: 45 },
      { poseId: 'str-plank', durationSec: 60, cue: 'Hold to finish.' },
      { poseId: 'str-burpee', durationSec: 45, cue: 'Last set. Empty the tank.' },
    ],
  },
]
